# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "bitbucket.org/atlassian/logevent"
  version = "1.0.2"

[[constraint]]
  name = "github.com/google/uuid"
  version = "v1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/rs/xstats"

[prune]
  go-tests = true
  unused-packages = true
